/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'doctorId' : DoctorId,
  'tokenNumber' : bigint,
  'patientId' : PatientId,
  'cancellationReason' : [] | [string],
  'date' : string,
  'createdAt' : Timestamp,
  'appointmentType' : AppointmentType,
  'notes' : [] | [string],
  'timeSlot' : string,
}
export type AppointmentId = bigint;
export type AppointmentStatus = { 'Confirmed' : null } |
  { 'Scheduled' : null } |
  { 'Cancelled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type AppointmentType = { 'OPD' : null } |
  { 'Telemedicine' : null };
export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'userId' : UserId,
  'entityId' : string,
  'timestamp' : Timestamp,
  'details' : string,
  'entityType' : string,
}
export interface Bed {
  'id' : BedId,
  'status' : BedStatus,
  'housekeepingStatus' : HousekeepingStatus,
  'patientId' : [] | [PatientId],
  'bedNumber' : string,
  'notes' : [] | [string],
  'wardId' : WardId,
}
export type BedId = bigint;
export type BedStatus = { 'Available' : null } |
  { 'Reserved' : null } |
  { 'Maintenance' : null } |
  { 'Occupied' : null };
export interface Bill {
  'id' : BillId,
  'status' : BillStatus,
  'insuranceClaimId' : [] | [string],
  'patientId' : PatientId,
  'createdAt' : Timestamp,
  'discountPercent' : bigint,
  'billType' : BillType,
  'totalAmount' : bigint,
  'visitId' : [] | [VisitId],
  'paymentMode' : [] | [PaymentMode],
  'items' : Array<BillItem>,
  'paidAmount' : bigint,
  'subtotal' : bigint,
}
export type BillId = bigint;
export interface BillItem {
  'serviceName' : string,
  'total' : bigint,
  'quantity' : bigint,
  'serviceId' : ServiceId,
  'unitPrice' : bigint,
}
export type BillStatus = { 'PartiallyPaid' : null } |
  { 'Refunded' : null } |
  { 'Paid' : null } |
  { 'Pending' : null };
export type BillType = { 'IPD' : null } |
  { 'OPD' : null };
export interface Consumable {
  'id' : ConsumableId,
  'name' : string,
  'quantity' : bigint,
  'reorderLevel' : bigint,
  'supplierId' : [] | [SupplierId],
  'unitCost' : bigint,
}
export type ConsumableId = bigint;
export interface Diagnosis {
  'icd10Code' : string,
  'description' : string,
  'diagnosisType' : DiagnosisType,
}
export type DiagnosisType = { 'Secondary' : null } |
  { 'Primary' : null };
export type DoctorId = bigint;
export interface DoctorProfile {
  'id' : DoctorId,
  'wardIds' : Array<string>,
  'userId' : UserId,
  'qualifications' : Array<string>,
  'specialization' : string,
  'schedule' : Array<WorkingHours>,
  'consultationFee' : bigint,
  'departmentId' : [] | [string],
}
export interface Drug {
  'id' : DrugId,
  'expiryDate' : string,
  'name' : string,
  'sellingPrice' : bigint,
  'quantityOnHand' : bigint,
  'isActive' : boolean,
  'dosageForm' : string,
  'strength' : string,
  'genericName' : string,
  'category' : string,
  'batchNo' : string,
  'reorderLevel' : bigint,
  'costPrice' : bigint,
  'supplierId' : [] | [SupplierId],
}
export type DrugId = bigint;
export interface DutyRoster {
  'id' : DutyRosterId,
  'status' : string,
  'userId' : UserId,
  'date' : string,
  'shift' : ShiftType,
  'wardId' : [] | [WardId],
}
export type DutyRosterId = bigint;
export type ERStatus = { 'Discharged' : null } |
  { 'InTreatment' : null } |
  { 'Waiting' : null };
export interface ERTriage {
  'id' : ERTriageId,
  'status' : ERStatus,
  'isTraumaCase' : boolean,
  'arrivalTime' : Timestamp,
  'patientId' : [] | [PatientId],
  'esiLevel' : bigint,
  'treatedByDoctorId' : [] | [DoctorId],
  'dischargedAt' : [] | [Timestamp],
  'bedId' : [] | [BedId],
  'isUnknownPatient' : boolean,
  'chiefComplaint' : string,
}
export type ERTriageId = bigint;
export type EquipmentId = bigint;
export interface EquipmentItem {
  'id' : EquipmentId,
  'status' : EquipmentStatus,
  'purchaseDate' : string,
  'nextServiceDate' : [] | [string],
  'cost' : bigint,
  'name' : string,
  'serialNumber' : string,
  'category' : string,
  'wardId' : [] | [WardId],
}
export type EquipmentStatus = { 'Decommissioned' : null } |
  { 'Active' : null } |
  { 'InMaintenance' : null };
export interface HospitalProfile {
  'id' : bigint,
  'timezone' : string,
  'name' : string,
  'email' : string,
  'logoUrl' : [] | [string],
  'currency' : string,
  'address' : string,
  'phone' : string,
  'branding' : [] | [string],
  'registrationNo' : string,
}
export type HousekeepingStatus = { 'Dirty' : null } |
  { 'InProgress' : null } |
  { 'Clean' : null };
export type ImagingType = { 'CT' : null } |
  { 'MRI' : null } |
  { 'XRay' : null } |
  { 'Ultrasound' : null } |
  { 'Other' : null };
export type IndentId = bigint;
export interface IndentItem {
  'itemId' : bigint,
  'itemName' : string,
  'quantity' : bigint,
}
export interface IndentRequest {
  'id' : IndentId,
  'status' : IndentStatus,
  'createdAt' : Timestamp,
  'requestedById' : UserId,
  'items' : Array<IndentItem>,
}
export type IndentStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Fulfilled' : null } |
  { 'Pending' : null };
export interface LabOrder {
  'id' : LabOrderId,
  'status' : LabStatus,
  'doctorId' : DoctorId,
  'isCritical' : boolean,
  'patientId' : PatientId,
  'createdAt' : Timestamp,
  'testName' : string,
  'testType' : string,
  'sampleCollectedAt' : [] | [Timestamp],
  'resultEnteredAt' : [] | [Timestamp],
  'referenceRange' : [] | [string],
  'notes' : [] | [string],
  'visitId' : [] | [VisitId],
  'resultFile' : [] | [string],
  'resultValue' : [] | [string],
}
export type LabOrderId = bigint;
export type LabStatus = { 'Ordered' : null } |
  { 'ResultReady' : null } |
  { 'Reported' : null } |
  { 'Processing' : null } |
  { 'SampleCollected' : null };
export interface LeaveRequest {
  'id' : LeaveRequestId,
  'status' : LeaveStatus,
  'endDate' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'startDate' : string,
  'reason' : string,
}
export type LeaveRequestId = bigint;
export type LeaveStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
  'priority' : NotificationPriority,
  'relatedId' : [] | [string],
}
export type NotificationId = bigint;
export type NotificationPriority = { 'Normal' : null } |
  { 'Critical' : null };
export type NotificationType = { 'CriticalLabAlert' : null } |
  { 'LowStockAlert' : null } |
  { 'ShiftReminder' : null } |
  { 'AppointmentReminder' : null } |
  { 'General' : null } |
  { 'DrugExpiryAlert' : null };
export interface POItem {
  'quantity' : bigint,
  'drugId' : DrugId,
  'unitCost' : bigint,
}
export type POStatus = { 'Draft' : null } |
  { 'Received' : null } |
  { 'Cancelled' : null } |
  { 'Submitted' : null };
export interface Patient {
  'id' : PatientId,
  'dob' : string,
  'mrn' : string,
  'admittedBedId' : [] | [BedId],
  'status' : PatientStatus,
  'insuranceProvider' : [] | [string],
  'admissionDate' : [] | [Timestamp],
  'insuranceId' : [] | [string],
  'createdAt' : Timestamp,
  'emergencyContact' : string,
  'photoUrl' : [] | [string],
  'email' : string,
  'bloodGroup' : string,
  'address' : string,
  'gender' : string,
  'wardId' : [] | [WardId],
  'phone' : string,
  'lastName' : string,
  'dischargeDate' : [] | [Timestamp],
  'allergies' : Array<string>,
  'firstName' : string,
}
export type PatientId = bigint;
export type PatientStatus = { 'OPD' : null } |
  { 'Discharged' : null } |
  { 'Admitted' : null } |
  { 'Transferred' : null };
export type PaymentMode = { 'UPI' : null } |
  { 'Insurance' : null } |
  { 'Card' : null } |
  { 'Cash' : null };
export interface Prescription {
  'status' : PrescriptionStatus,
  'duration' : string,
  'drugName' : string,
  'dose' : string,
  'dosageForm' : string,
  'notes' : [] | [string],
  'frequency' : string,
  'drugId' : [] | [DrugId],
}
export type PrescriptionStatus = { 'Dispensed' : null } |
  { 'Pending' : null };
export interface PurchaseOrder {
  'id' : PurchaseOrderId,
  'status' : POStatus,
  'createdAt' : Timestamp,
  'expectedDelivery' : [] | [string],
  'items' : Array<POItem>,
  'supplierId' : SupplierId,
}
export type PurchaseOrderId = bigint;
export interface RadiologyOrder {
  'id' : RadiologyOrderId,
  'reportUrl' : [] | [string],
  'status' : RadiologyStatus,
  'doctorId' : DoctorId,
  'patientId' : PatientId,
  'imagingType' : ImagingType,
  'createdAt' : Timestamp,
  'findings' : [] | [string],
  'radiologistId' : [] | [UserId],
  'clinicalIndication' : string,
  'bodyPart' : string,
}
export type RadiologyOrderId = bigint;
export type RadiologyStatus = { 'ImagingDone' : null } |
  { 'Ordered' : null } |
  { 'ReportReady' : null } |
  { 'Reported' : null };
export interface SOAPNotes {
  'assessment' : string,
  'objective' : string,
  'plan' : string,
  'subjective' : string,
}
export interface Service {
  'id' : ServiceId,
  'name' : string,
  'isActive' : boolean,
  'category' : string,
  'basePrice' : bigint,
}
export type ServiceId = bigint;
export type ShiftType = { 'Night' : null } |
  { 'Afternoon' : null } |
  { 'Morning' : null };
export interface Supplier {
  'id' : SupplierId,
  'categories' : Array<string>,
  'name' : string,
  'email' : string,
  'address' : string,
  'paymentTerms' : string,
  'phone' : string,
}
export type SupplierId = bigint;
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'status' : UserStatus,
  'principal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'departmentId' : [] | [string],
}
export type UserId = bigint;
export type UserRole = { 'Nurse' : null } |
  { 'Doctor' : null } |
  { 'SuperAdmin' : null } |
  { 'Receptionist' : null } |
  { 'Pharmacist' : null } |
  { 'Patient' : null } |
  { 'LabTechnician' : null };
export type UserStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Suspended' : null };
export interface Visit {
  'id' : VisitId,
  'doctorId' : DoctorId,
  'documentUrls' : Array<string>,
  'patientId' : PatientId,
  'createdAt' : Timestamp,
  'soapNotes' : SOAPNotes,
  'visitDate' : Timestamp,
  'diagnoses' : Array<Diagnosis>,
  'vitals' : [] | [VitalSigns],
  'prescriptions' : Array<Prescription>,
  'chiefComplaint' : string,
}
export type VisitId = bigint;
export interface VitalSigns {
  'bp' : string,
  'weight' : string,
  'height' : string,
  'temperature' : string,
  'spo2' : string,
  'recordedAt' : Timestamp,
  'pulse' : string,
}
export interface Ward {
  'id' : WardId,
  'name' : string,
  'totalBeds' : bigint,
  'isActive' : boolean,
  'wardType' : WardType,
  'inchargeNurseId' : [] | [UserId],
}
export type WardId = bigint;
export type WardType = { 'ICU' : null } |
  { 'Maternity' : null } |
  { 'Private' : null } |
  { 'General' : null } |
  { 'Emergency' : null };
export interface WorkingHours {
  'startTime' : string,
  'endTime' : string,
  'dayOfWeek' : bigint,
  'maxPatients' : bigint,
}
export interface _SERVICE {
  'admitPatient' : ActorMethod<[PatientId, BedId, WardId], boolean>,
  'cancelAppointment' : ActorMethod<[AppointmentId, string], boolean>,
  'createAppointment' : ActorMethod<
    [PatientId, DoctorId, string, string, AppointmentType, [] | [string]],
    Appointment
  >,
  'createBed' : ActorMethod<[WardId, string], Bed>,
  'createBill' : ActorMethod<
    [
      PatientId,
      [] | [VisitId],
      BillType,
      Array<BillItem>,
      bigint,
      [] | [PaymentMode],
    ],
    Bill
  >,
  'createConsumable' : ActorMethod<
    [string, bigint, bigint, bigint, [] | [SupplierId]],
    Consumable
  >,
  'createDoctorProfile' : ActorMethod<
    [UserId, string, Array<string>, [] | [string], bigint, Array<WorkingHours>],
    DoctorProfile
  >,
  'createDrug' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      bigint,
      bigint,
      [] | [SupplierId],
    ],
    Drug
  >,
  'createDutyRosterEntry' : ActorMethod<
    [UserId, string, ShiftType, [] | [WardId]],
    DutyRoster
  >,
  'createERTriage' : ActorMethod<
    [[] | [PatientId], bigint, string, boolean, boolean, [] | [BedId]],
    ERTriage
  >,
  'createEquipmentItem' : ActorMethod<
    [string, string, string, string, bigint, [] | [WardId]],
    EquipmentItem
  >,
  'createIndentRequest' : ActorMethod<
    [UserId, Array<IndentItem>],
    IndentRequest
  >,
  'createLabOrder' : ActorMethod<
    [PatientId, DoctorId, [] | [VisitId], string, string],
    LabOrder
  >,
  'createLeaveRequest' : ActorMethod<
    [UserId, string, string, string],
    LeaveRequest
  >,
  'createNotification' : ActorMethod<
    [
      UserId,
      NotificationType,
      string,
      string,
      NotificationPriority,
      [] | [string],
    ],
    Notification
  >,
  'createPatient' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    Patient
  >,
  'createPurchaseOrder' : ActorMethod<
    [SupplierId, Array<POItem>, [] | [string]],
    PurchaseOrder
  >,
  'createRadiologyOrder' : ActorMethod<
    [PatientId, DoctorId, ImagingType, string, string],
    RadiologyOrder
  >,
  'createService' : ActorMethod<[string, string, bigint], Service>,
  'createSupplier' : ActorMethod<
    [string, string, string, string, Array<string>, string],
    Supplier
  >,
  'createUser' : ActorMethod<
    [Principal, string, string, UserRole, [] | [string]],
    User
  >,
  'createVisit' : ActorMethod<
    [
      PatientId,
      DoctorId,
      string,
      SOAPNotes,
      Array<Diagnosis>,
      Array<Prescription>,
      [] | [VitalSigns],
    ],
    Visit
  >,
  'createWard' : ActorMethod<[string, WardType, bigint, [] | [UserId]], Ward>,
  'dischargePatient' : ActorMethod<[PatientId], boolean>,
  'dispensePrescription' : ActorMethod<[VisitId, string], boolean>,
  'getActiveERTriages' : ActorMethod<[], Array<ERTriage>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointmentsByDoctor' : ActorMethod<[DoctorId], Array<Appointment>>,
  'getAppointmentsByPatient' : ActorMethod<[PatientId], Array<Appointment>>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getBeds' : ActorMethod<[], Array<Bed>>,
  'getBedsByWard' : ActorMethod<[WardId], Array<Bed>>,
  'getBill' : ActorMethod<[BillId], [] | [Bill]>,
  'getBills' : ActorMethod<[], Array<Bill>>,
  'getBillsByPatient' : ActorMethod<[PatientId], Array<Bill>>,
  'getConsumables' : ActorMethod<[], Array<Consumable>>,
  'getDoctor' : ActorMethod<[DoctorId], [] | [DoctorProfile]>,
  'getDoctors' : ActorMethod<[], Array<DoctorProfile>>,
  'getDrug' : ActorMethod<[DrugId], [] | [Drug]>,
  'getDrugs' : ActorMethod<[], Array<Drug>>,
  'getDutyRoster' : ActorMethod<[], Array<DutyRoster>>,
  'getERTriages' : ActorMethod<[], Array<ERTriage>>,
  'getEquipment' : ActorMethod<[], Array<EquipmentItem>>,
  'getHospitalProfile' : ActorMethod<[], [] | [HospitalProfile]>,
  'getIndentRequests' : ActorMethod<[], Array<IndentRequest>>,
  'getLabOrder' : ActorMethod<[LabOrderId], [] | [LabOrder]>,
  'getLabOrders' : ActorMethod<[], Array<LabOrder>>,
  'getLabOrdersByPatient' : ActorMethod<[PatientId], Array<LabOrder>>,
  'getLeaveRequests' : ActorMethod<[], Array<LeaveRequest>>,
  'getLowStockDrugs' : ActorMethod<[], Array<Drug>>,
  'getNotifications' : ActorMethod<[UserId], Array<Notification>>,
  'getOPDQueue' : ActorMethod<[DoctorId, string], Array<Appointment>>,
  'getPatient' : ActorMethod<[PatientId], [] | [Patient]>,
  'getPatients' : ActorMethod<[], Array<Patient>>,
  'getPrescriptions' : ActorMethod<[PatientId], Array<Prescription>>,
  'getPrescriptionsByPatient' : ActorMethod<[PatientId], Array<Prescription>>,
  'getPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getRadiologyOrders' : ActorMethod<[], Array<RadiologyOrder>>,
  'getRadiologyOrdersByPatient' : ActorMethod<
    [PatientId],
    Array<RadiologyOrder>
  >,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'getVisit' : ActorMethod<[VisitId], [] | [Visit]>,
  'getVisits' : ActorMethod<[], Array<Visit>>,
  'getVisitsByPatient' : ActorMethod<[PatientId], Array<Visit>>,
  'getWard' : ActorMethod<[WardId], [] | [Ward]>,
  'getWards' : ActorMethod<[], Array<Ward>>,
  'initSampleData' : ActorMethod<[], string>,
  'markAllNotificationsRead' : ActorMethod<[UserId], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'transferPatient' : ActorMethod<[PatientId, WardId, BedId], boolean>,
  'updateAppointment' : ActorMethod<
    [AppointmentId, string, string, [] | [string]],
    boolean
  >,
  'updateBedStatus' : ActorMethod<
    [BedId, BedStatus, HousekeepingStatus, [] | [string]],
    boolean
  >,
  'updateBillPayment' : ActorMethod<[BillId, bigint, PaymentMode], boolean>,
  'updateDrugStock' : ActorMethod<[DrugId, bigint], boolean>,
  'updateERTriage' : ActorMethod<
    [ERTriageId, ERStatus, [] | [DoctorId], [] | [BedId]],
    boolean
  >,
  'updateHospitalProfile' : ActorMethod<
    [string, string, string, string, string, string, string],
    HospitalProfile
  >,
  'updateIndentStatus' : ActorMethod<[IndentId, IndentStatus], boolean>,
  'updateLabOrderResult' : ActorMethod<
    [
      LabOrderId,
      [] | [string],
      [] | [string],
      boolean,
      [] | [string],
      [] | [string],
    ],
    boolean
  >,
  'updateLabOrderStatus' : ActorMethod<[LabOrderId, LabStatus], boolean>,
  'updateLeaveStatus' : ActorMethod<[LeaveRequestId, LeaveStatus], boolean>,
  'updatePatient' : ActorMethod<
    [
      PatientId,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      [] | [string],
      [] | [string],
    ],
    boolean
  >,
  'updateRadiologyReport' : ActorMethod<
    [
      RadiologyOrderId,
      [] | [string],
      [] | [string],
      [] | [UserId],
      RadiologyStatus,
    ],
    boolean
  >,
  'updateUserStatus' : ActorMethod<[UserId, UserStatus], boolean>,
  'updateVisit' : ActorMethod<
    [
      VisitId,
      SOAPNotes,
      Array<Diagnosis>,
      Array<Prescription>,
      [] | [VitalSigns],
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];