/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PatientId = IDL.Nat;
export const BedId = IDL.Nat;
export const WardId = IDL.Nat;
export const AppointmentId = IDL.Nat;
export const DoctorId = IDL.Nat;
export const AppointmentType = IDL.Variant({
  'OPD' : IDL.Null,
  'Telemedicine' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Scheduled' : IDL.Null,
  'Cancelled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'doctorId' : DoctorId,
  'tokenNumber' : IDL.Nat,
  'patientId' : PatientId,
  'cancellationReason' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'appointmentType' : AppointmentType,
  'notes' : IDL.Opt(IDL.Text),
  'timeSlot' : IDL.Text,
});
export const BedStatus = IDL.Variant({
  'Available' : IDL.Null,
  'Reserved' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Occupied' : IDL.Null,
});
export const HousekeepingStatus = IDL.Variant({
  'Dirty' : IDL.Null,
  'InProgress' : IDL.Null,
  'Clean' : IDL.Null,
});
export const Bed = IDL.Record({
  'id' : BedId,
  'status' : BedStatus,
  'housekeepingStatus' : HousekeepingStatus,
  'patientId' : IDL.Opt(PatientId),
  'bedNumber' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'wardId' : WardId,
});
export const VisitId = IDL.Nat;
export const BillType = IDL.Variant({ 'IPD' : IDL.Null, 'OPD' : IDL.Null });
export const ServiceId = IDL.Nat;
export const BillItem = IDL.Record({
  'serviceName' : IDL.Text,
  'total' : IDL.Nat,
  'quantity' : IDL.Nat,
  'serviceId' : ServiceId,
  'unitPrice' : IDL.Nat,
});
export const PaymentMode = IDL.Variant({
  'UPI' : IDL.Null,
  'Insurance' : IDL.Null,
  'Card' : IDL.Null,
  'Cash' : IDL.Null,
});
export const BillId = IDL.Nat;
export const BillStatus = IDL.Variant({
  'PartiallyPaid' : IDL.Null,
  'Refunded' : IDL.Null,
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Bill = IDL.Record({
  'id' : BillId,
  'status' : BillStatus,
  'insuranceClaimId' : IDL.Opt(IDL.Text),
  'patientId' : PatientId,
  'createdAt' : Timestamp,
  'discountPercent' : IDL.Nat,
  'billType' : BillType,
  'totalAmount' : IDL.Nat,
  'visitId' : IDL.Opt(VisitId),
  'paymentMode' : IDL.Opt(PaymentMode),
  'items' : IDL.Vec(BillItem),
  'paidAmount' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const SupplierId = IDL.Nat;
export const ConsumableId = IDL.Nat;
export const Consumable = IDL.Record({
  'id' : ConsumableId,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'reorderLevel' : IDL.Nat,
  'supplierId' : IDL.Opt(SupplierId),
  'unitCost' : IDL.Nat,
});
export const UserId = IDL.Nat;
export const WorkingHours = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'dayOfWeek' : IDL.Nat,
  'maxPatients' : IDL.Nat,
});
export const DoctorProfile = IDL.Record({
  'id' : DoctorId,
  'wardIds' : IDL.Vec(IDL.Text),
  'userId' : UserId,
  'qualifications' : IDL.Vec(IDL.Text),
  'specialization' : IDL.Text,
  'schedule' : IDL.Vec(WorkingHours),
  'consultationFee' : IDL.Nat,
  'departmentId' : IDL.Opt(IDL.Text),
});
export const DrugId = IDL.Nat;
export const Drug = IDL.Record({
  'id' : DrugId,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'quantityOnHand' : IDL.Nat,
  'isActive' : IDL.Bool,
  'dosageForm' : IDL.Text,
  'strength' : IDL.Text,
  'genericName' : IDL.Text,
  'category' : IDL.Text,
  'batchNo' : IDL.Text,
  'reorderLevel' : IDL.Nat,
  'costPrice' : IDL.Nat,
  'supplierId' : IDL.Opt(SupplierId),
});
export const ShiftType = IDL.Variant({
  'Night' : IDL.Null,
  'Afternoon' : IDL.Null,
  'Morning' : IDL.Null,
});
export const DutyRosterId = IDL.Nat;
export const DutyRoster = IDL.Record({
  'id' : DutyRosterId,
  'status' : IDL.Text,
  'userId' : UserId,
  'date' : IDL.Text,
  'shift' : ShiftType,
  'wardId' : IDL.Opt(WardId),
});
export const ERTriageId = IDL.Nat;
export const ERStatus = IDL.Variant({
  'Discharged' : IDL.Null,
  'InTreatment' : IDL.Null,
  'Waiting' : IDL.Null,
});
export const ERTriage = IDL.Record({
  'id' : ERTriageId,
  'status' : ERStatus,
  'isTraumaCase' : IDL.Bool,
  'arrivalTime' : Timestamp,
  'patientId' : IDL.Opt(PatientId),
  'esiLevel' : IDL.Int,
  'treatedByDoctorId' : IDL.Opt(DoctorId),
  'dischargedAt' : IDL.Opt(Timestamp),
  'bedId' : IDL.Opt(BedId),
  'isUnknownPatient' : IDL.Bool,
  'chiefComplaint' : IDL.Text,
});
export const EquipmentId = IDL.Nat;
export const EquipmentStatus = IDL.Variant({
  'Decommissioned' : IDL.Null,
  'Active' : IDL.Null,
  'InMaintenance' : IDL.Null,
});
export const EquipmentItem = IDL.Record({
  'id' : EquipmentId,
  'status' : EquipmentStatus,
  'purchaseDate' : IDL.Text,
  'nextServiceDate' : IDL.Opt(IDL.Text),
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'serialNumber' : IDL.Text,
  'category' : IDL.Text,
  'wardId' : IDL.Opt(WardId),
});
export const IndentItem = IDL.Record({
  'itemId' : IDL.Nat,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const IndentId = IDL.Nat;
export const IndentStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Fulfilled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const IndentRequest = IDL.Record({
  'id' : IndentId,
  'status' : IndentStatus,
  'createdAt' : Timestamp,
  'requestedById' : UserId,
  'items' : IDL.Vec(IndentItem),
});
export const LabOrderId = IDL.Nat;
export const LabStatus = IDL.Variant({
  'Ordered' : IDL.Null,
  'ResultReady' : IDL.Null,
  'Reported' : IDL.Null,
  'Processing' : IDL.Null,
  'SampleCollected' : IDL.Null,
});
export const LabOrder = IDL.Record({
  'id' : LabOrderId,
  'status' : LabStatus,
  'doctorId' : DoctorId,
  'isCritical' : IDL.Bool,
  'patientId' : PatientId,
  'createdAt' : Timestamp,
  'testName' : IDL.Text,
  'testType' : IDL.Text,
  'sampleCollectedAt' : IDL.Opt(Timestamp),
  'resultEnteredAt' : IDL.Opt(Timestamp),
  'referenceRange' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'visitId' : IDL.Opt(VisitId),
  'resultFile' : IDL.Opt(IDL.Text),
  'resultValue' : IDL.Opt(IDL.Text),
});
export const LeaveRequestId = IDL.Nat;
export const LeaveStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const LeaveRequest = IDL.Record({
  'id' : LeaveRequestId,
  'status' : LeaveStatus,
  'endDate' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'startDate' : IDL.Text,
  'reason' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'CriticalLabAlert' : IDL.Null,
  'LowStockAlert' : IDL.Null,
  'ShiftReminder' : IDL.Null,
  'AppointmentReminder' : IDL.Null,
  'General' : IDL.Null,
  'DrugExpiryAlert' : IDL.Null,
});
export const NotificationPriority = IDL.Variant({
  'Normal' : IDL.Null,
  'Critical' : IDL.Null,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'priority' : NotificationPriority,
  'relatedId' : IDL.Opt(IDL.Text),
});
export const PatientStatus = IDL.Variant({
  'OPD' : IDL.Null,
  'Discharged' : IDL.Null,
  'Admitted' : IDL.Null,
  'Transferred' : IDL.Null,
});
export const Patient = IDL.Record({
  'id' : PatientId,
  'dob' : IDL.Text,
  'mrn' : IDL.Text,
  'admittedBedId' : IDL.Opt(BedId),
  'status' : PatientStatus,
  'insuranceProvider' : IDL.Opt(IDL.Text),
  'admissionDate' : IDL.Opt(Timestamp),
  'insuranceId' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'emergencyContact' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'wardId' : IDL.Opt(WardId),
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'dischargeDate' : IDL.Opt(Timestamp),
  'allergies' : IDL.Vec(IDL.Text),
  'firstName' : IDL.Text,
});
export const POItem = IDL.Record({
  'quantity' : IDL.Nat,
  'drugId' : DrugId,
  'unitCost' : IDL.Nat,
});
export const PurchaseOrderId = IDL.Nat;
export const POStatus = IDL.Variant({
  'Draft' : IDL.Null,
  'Received' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Submitted' : IDL.Null,
});
export const PurchaseOrder = IDL.Record({
  'id' : PurchaseOrderId,
  'status' : POStatus,
  'createdAt' : Timestamp,
  'expectedDelivery' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(POItem),
  'supplierId' : SupplierId,
});
export const ImagingType = IDL.Variant({
  'CT' : IDL.Null,
  'MRI' : IDL.Null,
  'XRay' : IDL.Null,
  'Ultrasound' : IDL.Null,
  'Other' : IDL.Null,
});
export const RadiologyOrderId = IDL.Nat;
export const RadiologyStatus = IDL.Variant({
  'ImagingDone' : IDL.Null,
  'Ordered' : IDL.Null,
  'ReportReady' : IDL.Null,
  'Reported' : IDL.Null,
});
export const RadiologyOrder = IDL.Record({
  'id' : RadiologyOrderId,
  'reportUrl' : IDL.Opt(IDL.Text),
  'status' : RadiologyStatus,
  'doctorId' : DoctorId,
  'patientId' : PatientId,
  'imagingType' : ImagingType,
  'createdAt' : Timestamp,
  'findings' : IDL.Opt(IDL.Text),
  'radiologistId' : IDL.Opt(UserId),
  'clinicalIndication' : IDL.Text,
  'bodyPart' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const Supplier = IDL.Record({
  'id' : SupplierId,
  'categories' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'paymentTerms' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'Nurse' : IDL.Null,
  'Doctor' : IDL.Null,
  'SuperAdmin' : IDL.Null,
  'Receptionist' : IDL.Null,
  'Pharmacist' : IDL.Null,
  'Patient' : IDL.Null,
  'LabTechnician' : IDL.Null,
});
export const UserStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Suspended' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'departmentId' : IDL.Opt(IDL.Text),
});
export const SOAPNotes = IDL.Record({
  'assessment' : IDL.Text,
  'objective' : IDL.Text,
  'plan' : IDL.Text,
  'subjective' : IDL.Text,
});
export const DiagnosisType = IDL.Variant({
  'Secondary' : IDL.Null,
  'Primary' : IDL.Null,
});
export const Diagnosis = IDL.Record({
  'icd10Code' : IDL.Text,
  'description' : IDL.Text,
  'diagnosisType' : DiagnosisType,
});
export const PrescriptionStatus = IDL.Variant({
  'Dispensed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Prescription = IDL.Record({
  'status' : PrescriptionStatus,
  'duration' : IDL.Text,
  'drugName' : IDL.Text,
  'dose' : IDL.Text,
  'dosageForm' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'frequency' : IDL.Text,
  'drugId' : IDL.Opt(DrugId),
});
export const VitalSigns = IDL.Record({
  'bp' : IDL.Text,
  'weight' : IDL.Text,
  'height' : IDL.Text,
  'temperature' : IDL.Text,
  'spo2' : IDL.Text,
  'recordedAt' : Timestamp,
  'pulse' : IDL.Text,
});
export const Visit = IDL.Record({
  'id' : VisitId,
  'doctorId' : DoctorId,
  'documentUrls' : IDL.Vec(IDL.Text),
  'patientId' : PatientId,
  'createdAt' : Timestamp,
  'soapNotes' : SOAPNotes,
  'visitDate' : Timestamp,
  'diagnoses' : IDL.Vec(Diagnosis),
  'vitals' : IDL.Opt(VitalSigns),
  'prescriptions' : IDL.Vec(Prescription),
  'chiefComplaint' : IDL.Text,
});
export const WardType = IDL.Variant({
  'ICU' : IDL.Null,
  'Maternity' : IDL.Null,
  'Private' : IDL.Null,
  'General' : IDL.Null,
  'Emergency' : IDL.Null,
});
export const Ward = IDL.Record({
  'id' : WardId,
  'name' : IDL.Text,
  'totalBeds' : IDL.Nat,
  'isActive' : IDL.Bool,
  'wardType' : WardType,
  'inchargeNurseId' : IDL.Opt(UserId),
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'userId' : UserId,
  'entityId' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
});
export const HospitalProfile = IDL.Record({
  'id' : IDL.Nat,
  'timezone' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'branding' : IDL.Opt(IDL.Text),
  'registrationNo' : IDL.Text,
});

export const idlService = IDL.Service({
  'admitPatient' : IDL.Func([PatientId, BedId, WardId], [IDL.Bool], []),
  'cancelAppointment' : IDL.Func([AppointmentId, IDL.Text], [IDL.Bool], []),
  'createAppointment' : IDL.Func(
      [
        PatientId,
        DoctorId,
        IDL.Text,
        IDL.Text,
        AppointmentType,
        IDL.Opt(IDL.Text),
      ],
      [Appointment],
      [],
    ),
  'createBed' : IDL.Func([WardId, IDL.Text], [Bed], []),
  'createBill' : IDL.Func(
      [
        PatientId,
        IDL.Opt(VisitId),
        BillType,
        IDL.Vec(BillItem),
        IDL.Nat,
        IDL.Opt(PaymentMode),
      ],
      [Bill],
      [],
    ),
  'createConsumable' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(SupplierId)],
      [Consumable],
      [],
    ),
  'createDoctorProfile' : IDL.Func(
      [
        UserId,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Vec(WorkingHours),
      ],
      [DoctorProfile],
      [],
    ),
  'createDrug' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(SupplierId),
      ],
      [Drug],
      [],
    ),
  'createDutyRosterEntry' : IDL.Func(
      [UserId, IDL.Text, ShiftType, IDL.Opt(WardId)],
      [DutyRoster],
      [],
    ),
  'createERTriage' : IDL.Func(
      [
        IDL.Opt(PatientId),
        IDL.Int,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(BedId),
      ],
      [ERTriage],
      [],
    ),
  'createEquipmentItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(WardId)],
      [EquipmentItem],
      [],
    ),
  'createIndentRequest' : IDL.Func(
      [UserId, IDL.Vec(IndentItem)],
      [IndentRequest],
      [],
    ),
  'createLabOrder' : IDL.Func(
      [PatientId, DoctorId, IDL.Opt(VisitId), IDL.Text, IDL.Text],
      [LabOrder],
      [],
    ),
  'createLeaveRequest' : IDL.Func(
      [UserId, IDL.Text, IDL.Text, IDL.Text],
      [LeaveRequest],
      [],
    ),
  'createNotification' : IDL.Func(
      [
        UserId,
        NotificationType,
        IDL.Text,
        IDL.Text,
        NotificationPriority,
        IDL.Opt(IDL.Text),
      ],
      [Notification],
      [],
    ),
  'createPatient' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Patient],
      [],
    ),
  'createPurchaseOrder' : IDL.Func(
      [SupplierId, IDL.Vec(POItem), IDL.Opt(IDL.Text)],
      [PurchaseOrder],
      [],
    ),
  'createRadiologyOrder' : IDL.Func(
      [PatientId, DoctorId, ImagingType, IDL.Text, IDL.Text],
      [RadiologyOrder],
      [],
    ),
  'createService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Service], []),
  'createSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [Supplier],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, UserRole, IDL.Opt(IDL.Text)],
      [User],
      [],
    ),
  'createVisit' : IDL.Func(
      [
        PatientId,
        DoctorId,
        IDL.Text,
        SOAPNotes,
        IDL.Vec(Diagnosis),
        IDL.Vec(Prescription),
        IDL.Opt(VitalSigns),
      ],
      [Visit],
      [],
    ),
  'createWard' : IDL.Func(
      [IDL.Text, WardType, IDL.Nat, IDL.Opt(UserId)],
      [Ward],
      [],
    ),
  'dischargePatient' : IDL.Func([PatientId], [IDL.Bool], []),
  'dispensePrescription' : IDL.Func([VisitId, IDL.Text], [IDL.Bool], []),
  'getActiveERTriages' : IDL.Func([], [IDL.Vec(ERTriage)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointmentsByDoctor' : IDL.Func(
      [DoctorId],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsByPatient' : IDL.Func(
      [PatientId],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getBeds' : IDL.Func([], [IDL.Vec(Bed)], ['query']),
  'getBedsByWard' : IDL.Func([WardId], [IDL.Vec(Bed)], ['query']),
  'getBill' : IDL.Func([BillId], [IDL.Opt(Bill)], ['query']),
  'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getBillsByPatient' : IDL.Func([PatientId], [IDL.Vec(Bill)], ['query']),
  'getConsumables' : IDL.Func([], [IDL.Vec(Consumable)], ['query']),
  'getDoctor' : IDL.Func([DoctorId], [IDL.Opt(DoctorProfile)], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
  'getDrug' : IDL.Func([DrugId], [IDL.Opt(Drug)], ['query']),
  'getDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getDutyRoster' : IDL.Func([], [IDL.Vec(DutyRoster)], ['query']),
  'getERTriages' : IDL.Func([], [IDL.Vec(ERTriage)], ['query']),
  'getEquipment' : IDL.Func([], [IDL.Vec(EquipmentItem)], ['query']),
  'getHospitalProfile' : IDL.Func([], [IDL.Opt(HospitalProfile)], ['query']),
  'getIndentRequests' : IDL.Func([], [IDL.Vec(IndentRequest)], ['query']),
  'getLabOrder' : IDL.Func([LabOrderId], [IDL.Opt(LabOrder)], ['query']),
  'getLabOrders' : IDL.Func([], [IDL.Vec(LabOrder)], ['query']),
  'getLabOrdersByPatient' : IDL.Func(
      [PatientId],
      [IDL.Vec(LabOrder)],
      ['query'],
    ),
  'getLeaveRequests' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
  'getLowStockDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
  'getNotifications' : IDL.Func([UserId], [IDL.Vec(Notification)], ['query']),
  'getOPDQueue' : IDL.Func(
      [DoctorId, IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getPatient' : IDL.Func([PatientId], [IDL.Opt(Patient)], ['query']),
  'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getPrescriptions' : IDL.Func(
      [PatientId],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getPrescriptionsByPatient' : IDL.Func(
      [PatientId],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getRadiologyOrders' : IDL.Func([], [IDL.Vec(RadiologyOrder)], ['query']),
  'getRadiologyOrdersByPatient' : IDL.Func(
      [PatientId],
      [IDL.Vec(RadiologyOrder)],
      ['query'],
    ),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getVisit' : IDL.Func([VisitId], [IDL.Opt(Visit)], ['query']),
  'getVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
  'getVisitsByPatient' : IDL.Func([PatientId], [IDL.Vec(Visit)], ['query']),
  'getWard' : IDL.Func([WardId], [IDL.Opt(Ward)], ['query']),
  'getWards' : IDL.Func([], [IDL.Vec(Ward)], ['query']),
  'initSampleData' : IDL.Func([], [IDL.Text], []),
  'markAllNotificationsRead' : IDL.Func([UserId], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'transferPatient' : IDL.Func([PatientId, WardId, BedId], [IDL.Bool], []),
  'updateAppointment' : IDL.Func(
      [AppointmentId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateBedStatus' : IDL.Func(
      [BedId, BedStatus, HousekeepingStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateBillPayment' : IDL.Func(
      [BillId, IDL.Nat, PaymentMode],
      [IDL.Bool],
      [],
    ),
  'updateDrugStock' : IDL.Func([DrugId, IDL.Int], [IDL.Bool], []),
  'updateERTriage' : IDL.Func(
      [ERTriageId, ERStatus, IDL.Opt(DoctorId), IDL.Opt(BedId)],
      [IDL.Bool],
      [],
    ),
  'updateHospitalProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [HospitalProfile],
      [],
    ),
  'updateIndentStatus' : IDL.Func([IndentId, IndentStatus], [IDL.Bool], []),
  'updateLabOrderResult' : IDL.Func(
      [
        LabOrderId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'updateLabOrderStatus' : IDL.Func([LabOrderId, LabStatus], [IDL.Bool], []),
  'updateLeaveStatus' : IDL.Func([LeaveRequestId, LeaveStatus], [IDL.Bool], []),
  'updatePatient' : IDL.Func(
      [
        PatientId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
  'updateRadiologyReport' : IDL.Func(
      [
        RadiologyOrderId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(UserId),
        RadiologyStatus,
      ],
      [IDL.Bool],
      [],
    ),
  'updateUserStatus' : IDL.Func([UserId, UserStatus], [IDL.Bool], []),
  'updateVisit' : IDL.Func(
      [
        VisitId,
        SOAPNotes,
        IDL.Vec(Diagnosis),
        IDL.Vec(Prescription),
        IDL.Opt(VitalSigns),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PatientId = IDL.Nat;
  const BedId = IDL.Nat;
  const WardId = IDL.Nat;
  const AppointmentId = IDL.Nat;
  const DoctorId = IDL.Nat;
  const AppointmentType = IDL.Variant({
    'OPD' : IDL.Null,
    'Telemedicine' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Scheduled' : IDL.Null,
    'Cancelled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'status' : AppointmentStatus,
    'doctorId' : DoctorId,
    'tokenNumber' : IDL.Nat,
    'patientId' : PatientId,
    'cancellationReason' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'appointmentType' : AppointmentType,
    'notes' : IDL.Opt(IDL.Text),
    'timeSlot' : IDL.Text,
  });
  const BedStatus = IDL.Variant({
    'Available' : IDL.Null,
    'Reserved' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Occupied' : IDL.Null,
  });
  const HousekeepingStatus = IDL.Variant({
    'Dirty' : IDL.Null,
    'InProgress' : IDL.Null,
    'Clean' : IDL.Null,
  });
  const Bed = IDL.Record({
    'id' : BedId,
    'status' : BedStatus,
    'housekeepingStatus' : HousekeepingStatus,
    'patientId' : IDL.Opt(PatientId),
    'bedNumber' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'wardId' : WardId,
  });
  const VisitId = IDL.Nat;
  const BillType = IDL.Variant({ 'IPD' : IDL.Null, 'OPD' : IDL.Null });
  const ServiceId = IDL.Nat;
  const BillItem = IDL.Record({
    'serviceName' : IDL.Text,
    'total' : IDL.Nat,
    'quantity' : IDL.Nat,
    'serviceId' : ServiceId,
    'unitPrice' : IDL.Nat,
  });
  const PaymentMode = IDL.Variant({
    'UPI' : IDL.Null,
    'Insurance' : IDL.Null,
    'Card' : IDL.Null,
    'Cash' : IDL.Null,
  });
  const BillId = IDL.Nat;
  const BillStatus = IDL.Variant({
    'PartiallyPaid' : IDL.Null,
    'Refunded' : IDL.Null,
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Bill = IDL.Record({
    'id' : BillId,
    'status' : BillStatus,
    'insuranceClaimId' : IDL.Opt(IDL.Text),
    'patientId' : PatientId,
    'createdAt' : Timestamp,
    'discountPercent' : IDL.Nat,
    'billType' : BillType,
    'totalAmount' : IDL.Nat,
    'visitId' : IDL.Opt(VisitId),
    'paymentMode' : IDL.Opt(PaymentMode),
    'items' : IDL.Vec(BillItem),
    'paidAmount' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const SupplierId = IDL.Nat;
  const ConsumableId = IDL.Nat;
  const Consumable = IDL.Record({
    'id' : ConsumableId,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'reorderLevel' : IDL.Nat,
    'supplierId' : IDL.Opt(SupplierId),
    'unitCost' : IDL.Nat,
  });
  const UserId = IDL.Nat;
  const WorkingHours = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'dayOfWeek' : IDL.Nat,
    'maxPatients' : IDL.Nat,
  });
  const DoctorProfile = IDL.Record({
    'id' : DoctorId,
    'wardIds' : IDL.Vec(IDL.Text),
    'userId' : UserId,
    'qualifications' : IDL.Vec(IDL.Text),
    'specialization' : IDL.Text,
    'schedule' : IDL.Vec(WorkingHours),
    'consultationFee' : IDL.Nat,
    'departmentId' : IDL.Opt(IDL.Text),
  });
  const DrugId = IDL.Nat;
  const Drug = IDL.Record({
    'id' : DrugId,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'quantityOnHand' : IDL.Nat,
    'isActive' : IDL.Bool,
    'dosageForm' : IDL.Text,
    'strength' : IDL.Text,
    'genericName' : IDL.Text,
    'category' : IDL.Text,
    'batchNo' : IDL.Text,
    'reorderLevel' : IDL.Nat,
    'costPrice' : IDL.Nat,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const ShiftType = IDL.Variant({
    'Night' : IDL.Null,
    'Afternoon' : IDL.Null,
    'Morning' : IDL.Null,
  });
  const DutyRosterId = IDL.Nat;
  const DutyRoster = IDL.Record({
    'id' : DutyRosterId,
    'status' : IDL.Text,
    'userId' : UserId,
    'date' : IDL.Text,
    'shift' : ShiftType,
    'wardId' : IDL.Opt(WardId),
  });
  const ERTriageId = IDL.Nat;
  const ERStatus = IDL.Variant({
    'Discharged' : IDL.Null,
    'InTreatment' : IDL.Null,
    'Waiting' : IDL.Null,
  });
  const ERTriage = IDL.Record({
    'id' : ERTriageId,
    'status' : ERStatus,
    'isTraumaCase' : IDL.Bool,
    'arrivalTime' : Timestamp,
    'patientId' : IDL.Opt(PatientId),
    'esiLevel' : IDL.Int,
    'treatedByDoctorId' : IDL.Opt(DoctorId),
    'dischargedAt' : IDL.Opt(Timestamp),
    'bedId' : IDL.Opt(BedId),
    'isUnknownPatient' : IDL.Bool,
    'chiefComplaint' : IDL.Text,
  });
  const EquipmentId = IDL.Nat;
  const EquipmentStatus = IDL.Variant({
    'Decommissioned' : IDL.Null,
    'Active' : IDL.Null,
    'InMaintenance' : IDL.Null,
  });
  const EquipmentItem = IDL.Record({
    'id' : EquipmentId,
    'status' : EquipmentStatus,
    'purchaseDate' : IDL.Text,
    'nextServiceDate' : IDL.Opt(IDL.Text),
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'serialNumber' : IDL.Text,
    'category' : IDL.Text,
    'wardId' : IDL.Opt(WardId),
  });
  const IndentItem = IDL.Record({
    'itemId' : IDL.Nat,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const IndentId = IDL.Nat;
  const IndentStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Fulfilled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const IndentRequest = IDL.Record({
    'id' : IndentId,
    'status' : IndentStatus,
    'createdAt' : Timestamp,
    'requestedById' : UserId,
    'items' : IDL.Vec(IndentItem),
  });
  const LabOrderId = IDL.Nat;
  const LabStatus = IDL.Variant({
    'Ordered' : IDL.Null,
    'ResultReady' : IDL.Null,
    'Reported' : IDL.Null,
    'Processing' : IDL.Null,
    'SampleCollected' : IDL.Null,
  });
  const LabOrder = IDL.Record({
    'id' : LabOrderId,
    'status' : LabStatus,
    'doctorId' : DoctorId,
    'isCritical' : IDL.Bool,
    'patientId' : PatientId,
    'createdAt' : Timestamp,
    'testName' : IDL.Text,
    'testType' : IDL.Text,
    'sampleCollectedAt' : IDL.Opt(Timestamp),
    'resultEnteredAt' : IDL.Opt(Timestamp),
    'referenceRange' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'visitId' : IDL.Opt(VisitId),
    'resultFile' : IDL.Opt(IDL.Text),
    'resultValue' : IDL.Opt(IDL.Text),
  });
  const LeaveRequestId = IDL.Nat;
  const LeaveStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const LeaveRequest = IDL.Record({
    'id' : LeaveRequestId,
    'status' : LeaveStatus,
    'endDate' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'startDate' : IDL.Text,
    'reason' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'CriticalLabAlert' : IDL.Null,
    'LowStockAlert' : IDL.Null,
    'ShiftReminder' : IDL.Null,
    'AppointmentReminder' : IDL.Null,
    'General' : IDL.Null,
    'DrugExpiryAlert' : IDL.Null,
  });
  const NotificationPriority = IDL.Variant({
    'Normal' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'priority' : NotificationPriority,
    'relatedId' : IDL.Opt(IDL.Text),
  });
  const PatientStatus = IDL.Variant({
    'OPD' : IDL.Null,
    'Discharged' : IDL.Null,
    'Admitted' : IDL.Null,
    'Transferred' : IDL.Null,
  });
  const Patient = IDL.Record({
    'id' : PatientId,
    'dob' : IDL.Text,
    'mrn' : IDL.Text,
    'admittedBedId' : IDL.Opt(BedId),
    'status' : PatientStatus,
    'insuranceProvider' : IDL.Opt(IDL.Text),
    'admissionDate' : IDL.Opt(Timestamp),
    'insuranceId' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'emergencyContact' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'wardId' : IDL.Opt(WardId),
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'dischargeDate' : IDL.Opt(Timestamp),
    'allergies' : IDL.Vec(IDL.Text),
    'firstName' : IDL.Text,
  });
  const POItem = IDL.Record({
    'quantity' : IDL.Nat,
    'drugId' : DrugId,
    'unitCost' : IDL.Nat,
  });
  const PurchaseOrderId = IDL.Nat;
  const POStatus = IDL.Variant({
    'Draft' : IDL.Null,
    'Received' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Submitted' : IDL.Null,
  });
  const PurchaseOrder = IDL.Record({
    'id' : PurchaseOrderId,
    'status' : POStatus,
    'createdAt' : Timestamp,
    'expectedDelivery' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(POItem),
    'supplierId' : SupplierId,
  });
  const ImagingType = IDL.Variant({
    'CT' : IDL.Null,
    'MRI' : IDL.Null,
    'XRay' : IDL.Null,
    'Ultrasound' : IDL.Null,
    'Other' : IDL.Null,
  });
  const RadiologyOrderId = IDL.Nat;
  const RadiologyStatus = IDL.Variant({
    'ImagingDone' : IDL.Null,
    'Ordered' : IDL.Null,
    'ReportReady' : IDL.Null,
    'Reported' : IDL.Null,
  });
  const RadiologyOrder = IDL.Record({
    'id' : RadiologyOrderId,
    'reportUrl' : IDL.Opt(IDL.Text),
    'status' : RadiologyStatus,
    'doctorId' : DoctorId,
    'patientId' : PatientId,
    'imagingType' : ImagingType,
    'createdAt' : Timestamp,
    'findings' : IDL.Opt(IDL.Text),
    'radiologistId' : IDL.Opt(UserId),
    'clinicalIndication' : IDL.Text,
    'bodyPart' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const Supplier = IDL.Record({
    'id' : SupplierId,
    'categories' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'paymentTerms' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'Nurse' : IDL.Null,
    'Doctor' : IDL.Null,
    'SuperAdmin' : IDL.Null,
    'Receptionist' : IDL.Null,
    'Pharmacist' : IDL.Null,
    'Patient' : IDL.Null,
    'LabTechnician' : IDL.Null,
  });
  const UserStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Suspended' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'departmentId' : IDL.Opt(IDL.Text),
  });
  const SOAPNotes = IDL.Record({
    'assessment' : IDL.Text,
    'objective' : IDL.Text,
    'plan' : IDL.Text,
    'subjective' : IDL.Text,
  });
  const DiagnosisType = IDL.Variant({
    'Secondary' : IDL.Null,
    'Primary' : IDL.Null,
  });
  const Diagnosis = IDL.Record({
    'icd10Code' : IDL.Text,
    'description' : IDL.Text,
    'diagnosisType' : DiagnosisType,
  });
  const PrescriptionStatus = IDL.Variant({
    'Dispensed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Prescription = IDL.Record({
    'status' : PrescriptionStatus,
    'duration' : IDL.Text,
    'drugName' : IDL.Text,
    'dose' : IDL.Text,
    'dosageForm' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'frequency' : IDL.Text,
    'drugId' : IDL.Opt(DrugId),
  });
  const VitalSigns = IDL.Record({
    'bp' : IDL.Text,
    'weight' : IDL.Text,
    'height' : IDL.Text,
    'temperature' : IDL.Text,
    'spo2' : IDL.Text,
    'recordedAt' : Timestamp,
    'pulse' : IDL.Text,
  });
  const Visit = IDL.Record({
    'id' : VisitId,
    'doctorId' : DoctorId,
    'documentUrls' : IDL.Vec(IDL.Text),
    'patientId' : PatientId,
    'createdAt' : Timestamp,
    'soapNotes' : SOAPNotes,
    'visitDate' : Timestamp,
    'diagnoses' : IDL.Vec(Diagnosis),
    'vitals' : IDL.Opt(VitalSigns),
    'prescriptions' : IDL.Vec(Prescription),
    'chiefComplaint' : IDL.Text,
  });
  const WardType = IDL.Variant({
    'ICU' : IDL.Null,
    'Maternity' : IDL.Null,
    'Private' : IDL.Null,
    'General' : IDL.Null,
    'Emergency' : IDL.Null,
  });
  const Ward = IDL.Record({
    'id' : WardId,
    'name' : IDL.Text,
    'totalBeds' : IDL.Nat,
    'isActive' : IDL.Bool,
    'wardType' : WardType,
    'inchargeNurseId' : IDL.Opt(UserId),
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'userId' : UserId,
    'entityId' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
  });
  const HospitalProfile = IDL.Record({
    'id' : IDL.Nat,
    'timezone' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'branding' : IDL.Opt(IDL.Text),
    'registrationNo' : IDL.Text,
  });
  
  return IDL.Service({
    'admitPatient' : IDL.Func([PatientId, BedId, WardId], [IDL.Bool], []),
    'cancelAppointment' : IDL.Func([AppointmentId, IDL.Text], [IDL.Bool], []),
    'createAppointment' : IDL.Func(
        [
          PatientId,
          DoctorId,
          IDL.Text,
          IDL.Text,
          AppointmentType,
          IDL.Opt(IDL.Text),
        ],
        [Appointment],
        [],
      ),
    'createBed' : IDL.Func([WardId, IDL.Text], [Bed], []),
    'createBill' : IDL.Func(
        [
          PatientId,
          IDL.Opt(VisitId),
          BillType,
          IDL.Vec(BillItem),
          IDL.Nat,
          IDL.Opt(PaymentMode),
        ],
        [Bill],
        [],
      ),
    'createConsumable' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(SupplierId)],
        [Consumable],
        [],
      ),
    'createDoctorProfile' : IDL.Func(
        [
          UserId,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Vec(WorkingHours),
        ],
        [DoctorProfile],
        [],
      ),
    'createDrug' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(SupplierId),
        ],
        [Drug],
        [],
      ),
    'createDutyRosterEntry' : IDL.Func(
        [UserId, IDL.Text, ShiftType, IDL.Opt(WardId)],
        [DutyRoster],
        [],
      ),
    'createERTriage' : IDL.Func(
        [
          IDL.Opt(PatientId),
          IDL.Int,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(BedId),
        ],
        [ERTriage],
        [],
      ),
    'createEquipmentItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(WardId)],
        [EquipmentItem],
        [],
      ),
    'createIndentRequest' : IDL.Func(
        [UserId, IDL.Vec(IndentItem)],
        [IndentRequest],
        [],
      ),
    'createLabOrder' : IDL.Func(
        [PatientId, DoctorId, IDL.Opt(VisitId), IDL.Text, IDL.Text],
        [LabOrder],
        [],
      ),
    'createLeaveRequest' : IDL.Func(
        [UserId, IDL.Text, IDL.Text, IDL.Text],
        [LeaveRequest],
        [],
      ),
    'createNotification' : IDL.Func(
        [
          UserId,
          NotificationType,
          IDL.Text,
          IDL.Text,
          NotificationPriority,
          IDL.Opt(IDL.Text),
        ],
        [Notification],
        [],
      ),
    'createPatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Patient],
        [],
      ),
    'createPurchaseOrder' : IDL.Func(
        [SupplierId, IDL.Vec(POItem), IDL.Opt(IDL.Text)],
        [PurchaseOrder],
        [],
      ),
    'createRadiologyOrder' : IDL.Func(
        [PatientId, DoctorId, ImagingType, IDL.Text, IDL.Text],
        [RadiologyOrder],
        [],
      ),
    'createService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Service], []),
    'createSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [Supplier],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, UserRole, IDL.Opt(IDL.Text)],
        [User],
        [],
      ),
    'createVisit' : IDL.Func(
        [
          PatientId,
          DoctorId,
          IDL.Text,
          SOAPNotes,
          IDL.Vec(Diagnosis),
          IDL.Vec(Prescription),
          IDL.Opt(VitalSigns),
        ],
        [Visit],
        [],
      ),
    'createWard' : IDL.Func(
        [IDL.Text, WardType, IDL.Nat, IDL.Opt(UserId)],
        [Ward],
        [],
      ),
    'dischargePatient' : IDL.Func([PatientId], [IDL.Bool], []),
    'dispensePrescription' : IDL.Func([VisitId, IDL.Text], [IDL.Bool], []),
    'getActiveERTriages' : IDL.Func([], [IDL.Vec(ERTriage)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointmentsByDoctor' : IDL.Func(
        [DoctorId],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsByPatient' : IDL.Func(
        [PatientId],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getBeds' : IDL.Func([], [IDL.Vec(Bed)], ['query']),
    'getBedsByWard' : IDL.Func([WardId], [IDL.Vec(Bed)], ['query']),
    'getBill' : IDL.Func([BillId], [IDL.Opt(Bill)], ['query']),
    'getBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getBillsByPatient' : IDL.Func([PatientId], [IDL.Vec(Bill)], ['query']),
    'getConsumables' : IDL.Func([], [IDL.Vec(Consumable)], ['query']),
    'getDoctor' : IDL.Func([DoctorId], [IDL.Opt(DoctorProfile)], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
    'getDrug' : IDL.Func([DrugId], [IDL.Opt(Drug)], ['query']),
    'getDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getDutyRoster' : IDL.Func([], [IDL.Vec(DutyRoster)], ['query']),
    'getERTriages' : IDL.Func([], [IDL.Vec(ERTriage)], ['query']),
    'getEquipment' : IDL.Func([], [IDL.Vec(EquipmentItem)], ['query']),
    'getHospitalProfile' : IDL.Func([], [IDL.Opt(HospitalProfile)], ['query']),
    'getIndentRequests' : IDL.Func([], [IDL.Vec(IndentRequest)], ['query']),
    'getLabOrder' : IDL.Func([LabOrderId], [IDL.Opt(LabOrder)], ['query']),
    'getLabOrders' : IDL.Func([], [IDL.Vec(LabOrder)], ['query']),
    'getLabOrdersByPatient' : IDL.Func(
        [PatientId],
        [IDL.Vec(LabOrder)],
        ['query'],
      ),
    'getLeaveRequests' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
    'getLowStockDrugs' : IDL.Func([], [IDL.Vec(Drug)], ['query']),
    'getNotifications' : IDL.Func([UserId], [IDL.Vec(Notification)], ['query']),
    'getOPDQueue' : IDL.Func(
        [DoctorId, IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getPatient' : IDL.Func([PatientId], [IDL.Opt(Patient)], ['query']),
    'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getPrescriptions' : IDL.Func(
        [PatientId],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getPrescriptionsByPatient' : IDL.Func(
        [PatientId],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getRadiologyOrders' : IDL.Func([], [IDL.Vec(RadiologyOrder)], ['query']),
    'getRadiologyOrdersByPatient' : IDL.Func(
        [PatientId],
        [IDL.Vec(RadiologyOrder)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getVisit' : IDL.Func([VisitId], [IDL.Opt(Visit)], ['query']),
    'getVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
    'getVisitsByPatient' : IDL.Func([PatientId], [IDL.Vec(Visit)], ['query']),
    'getWard' : IDL.Func([WardId], [IDL.Opt(Ward)], ['query']),
    'getWards' : IDL.Func([], [IDL.Vec(Ward)], ['query']),
    'initSampleData' : IDL.Func([], [IDL.Text], []),
    'markAllNotificationsRead' : IDL.Func([UserId], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'transferPatient' : IDL.Func([PatientId, WardId, BedId], [IDL.Bool], []),
    'updateAppointment' : IDL.Func(
        [AppointmentId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateBedStatus' : IDL.Func(
        [BedId, BedStatus, HousekeepingStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateBillPayment' : IDL.Func(
        [BillId, IDL.Nat, PaymentMode],
        [IDL.Bool],
        [],
      ),
    'updateDrugStock' : IDL.Func([DrugId, IDL.Int], [IDL.Bool], []),
    'updateERTriage' : IDL.Func(
        [ERTriageId, ERStatus, IDL.Opt(DoctorId), IDL.Opt(BedId)],
        [IDL.Bool],
        [],
      ),
    'updateHospitalProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [HospitalProfile],
        [],
      ),
    'updateIndentStatus' : IDL.Func([IndentId, IndentStatus], [IDL.Bool], []),
    'updateLabOrderResult' : IDL.Func(
        [
          LabOrderId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'updateLabOrderStatus' : IDL.Func([LabOrderId, LabStatus], [IDL.Bool], []),
    'updateLeaveStatus' : IDL.Func(
        [LeaveRequestId, LeaveStatus],
        [IDL.Bool],
        [],
      ),
    'updatePatient' : IDL.Func(
        [
          PatientId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
    'updateRadiologyReport' : IDL.Func(
        [
          RadiologyOrderId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(UserId),
          RadiologyStatus,
        ],
        [IDL.Bool],
        [],
      ),
    'updateUserStatus' : IDL.Func([UserId, UserStatus], [IDL.Bool], []),
    'updateVisit' : IDL.Func(
        [
          VisitId,
          SOAPNotes,
          IDL.Vec(Diagnosis),
          IDL.Vec(Prescription),
          IDL.Opt(VitalSigns),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };